export const EXECUTION_POLL_INTERVAL_MS = 1000;
export const EXECUTION_HISTORY_REFRESH_INTERVAL_MS = 5000;
export const ACTIVE_TRIGGERS_REFRESH_INTERVAL_MS = 10000;
export const AUTO_REFRESH_PAUSE_DURATION_MS = 30000;
export const STATISTICS_REFRESH_INTERVAL_MS = 30000;
export const PERFORMANCE_REFRESH_INTERVAL_MS = 30000;

